# 3. Fibonacci Sequence
# # Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# # 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 0
n = 0
n_current = 1
while n_current < 4000001:
    if n_current % 2 == 0:
        sum += n_current
    n_current += n
    n = n_current - n
print(sum)

